name: Daily Counter Update

on:
  schedule:
    - cron: '0 5 * * *' # Todos los días a las 5AM UTC
  workflow_dispatch:     # También puedes ejecutarlo manualmente

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update lastUpdate.txt
        run: |
          # Lee el número actual (si no existe, usa 0)
          count=$(cat lastUpdate.txt 2>/dev/null || echo 0)
          # Suma 1
          new_count=$((count + 1))
          # Guarda el nuevo valor
          echo $new_count > lastUpdate.txt
          echo "Updated lastUpdate.txt to $new_count"

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "action@github.com"
          git add lastUpdate.txt
          git commit -m "🔁 Daily update: $new_count"
          git push
