name: Metrics

on:
  schedule: [{cron: "0 0 * * *"}]  # Corre todos los días
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Sunshide12
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota
