name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # 7:00 p. m. COL (00:00 UTC)
    - cron: "0 12 * * *"  # 7:00 a. m. COL (12:00 UTC)
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Sunshide12
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Bogota

          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_languages: yes
          plugin_wakatime_repositories: yes
